bug: added intentional bug to test workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -21,5 +21,5 @@ jobs:
       - name: Run tests
         run: go test ./...
 
-      - name: Force Failure
-        run: (exit 1)
+      # - name: Force Failure
+      #   run: (exit 1)
