go version

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,5 +19,7 @@ jobs:
         with:
           go-version: "1.26.0"
 
-      - name: Force Failure
-        run: (exit 1)
+      # - name: Force Failure
+      #   run: (exit 1)
+      - name: Display Go version
+        run: go version
